<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-gb" xml:lang="en-gb">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="en-gb" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<title>&#1488;&#1511;&#1493;&#1500;&#1493;&#1511;&#1493; &#1492;&#1508;&#1493;&#1512;&#1493;&#1501; &bull; View forum - @@@@@ אקולוקו הסיירת @@@@@</title>

<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:      
	
	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Enter the page number you wish to go to.:';
	var on_page = '1';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	
	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/prosilver/template/styleswitcher.js"></script>
<script type="text/javascript" src="./styles/prosilver/template/forum_fn.js"></script>

<link href="./styles/prosilver/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.php?sid=026da0ceed002d24d07e728d2bf8d497&amp;id=1&amp;lang=en" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./styles/prosilver/theme/normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="./styles/prosilver/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./styles/prosilver/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" />


</head>

<body id="phpbb" class="section-viewforum ltr">

<div id="wrap">
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<div id="site-description">
				<a href="./index.php" title="Board index" id="logo"><img src="./styles/prosilver/imageset/site_logo.gif" width="139" height="52" alt="" title="" /></a>
				<h1>&#1488;&#1511;&#1493;&#1500;&#1493;&#1511;&#1493; &#1492;&#1508;&#1493;&#1512;&#1493;&#1501;</h1>
				<p>ekoloko</p>
				<p style="display: none;"><a href="#start_here">Skip to content</a></p>
			</div>

		
			<span class="corners-bottom"><span></span></span></div>
		</div>

		<div class="navbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<ul class="linklist navlinks">
				<li class="icon-home"><a href="./index.php" accesskey="h">Board index</a>  <strong>&#8249;</strong> <a href="./viewforum.php?f=3">@@@@@ אקולוקו הסיירת @@@@@</a></li>

				<li class="rightside"><a href="#" onclick="fontsizeup(); return false;" onkeypress="fontsizeup(); return false;" class="fontsize" title="Change font size">Change font size</a></li>

							</ul>

			
			<ul class="linklist rightside">
				<li class="icon-faq"><a href="./faq.php" title="Frequently Asked Questions">FAQ</a></li>
							</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>

	</div>

	<a name="start_here"></a>
	<div id="page-body">
		
		 <h2><a href="./viewforum.php?f=3&amp;st=0&amp;sk=t&amp;sd=d&amp;start=0">@@@@@ אקולוקו הסיירת @@@@@</a></h2>

	<div class="topic-actions" >

			<div class="pagination">
			2 topics &bull; Page <strong>1</strong> of <strong>1</strong>		</div>
	
	</div>
		<div class="forumbg announcement">
		<div class="inner"><span class="corners-top"><span></span></span>
		<ul class="topiclist">
			<li class="header">
				<dl class="icon">
					<dt>Topics</dt>
					<dd class="posts">Replies</dd>
					<dd class="views">Views</dd>
					<dd class="lastpost"><span>Last post</span></dd>
				</dl>
			</li>
		</ul>
		<ul class="topiclist topics">
		
		<li class="row bg1 sticky">
			<dl class="icon" style="background-image: url(./styles/prosilver/imageset/sticky_read.gif); background-repeat: no-repeat;">
				<dt title="No new posts"><a href="./viewtopic.php?f=3&amp;t=13" class="topictitle">אילו משחקים אתם הכי אוהבים ?</a>
					<br />
					<strong class="pagination"><span><a href="./viewtopic.php?f=3&amp;t=13&amp;start=0">1</a> ... <a href="./viewtopic.php?f=3&amp;t=13&amp;start=220">23</a><span class="page-sep">, </span><a href="./viewtopic.php?f=3&amp;t=13&amp;start=230">24</a><span class="page-sep">, </span><a href="./viewtopic.php?f=3&amp;t=13&amp;start=240">25</a></span></strong>by <span style="color: #AA0000;" class="username-coloured">admin</span> on Fri Sep 12, 2008 8:06 pm 
				</dt>
				<dd class="posts">249 <dfn>Replies</dfn></dd>
				<dd class="views">285 <dfn>Views</dfn></dd>
				<dd class="lastpost"><span><dfn>Last post </dfn>by seoceo2008					<a href="./viewtopic.php?f=3&amp;t=13&amp;p=328#p328"><img src="./styles/prosilver/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Thu Jan 29, 2009 5:29 am</span>
				</dd>
			</dl>
		</li>

		
		<li class="row bg2">
			<dl class="icon" style="background-image: url(./styles/prosilver/imageset/topic_read_hot.gif); background-repeat: no-repeat;">
				<dt title="No new posts"><a href="./viewtopic.php?f=3&amp;t=11" class="topictitle">הפורום שלנו חברי סיירת אקולוקו</a>
					<br />
					<strong class="pagination"><span><a href="./viewtopic.php?f=3&amp;t=11&amp;start=0">1</a> ... <a href="./viewtopic.php?f=3&amp;t=11&amp;start=50">6</a><span class="page-sep">, </span><a href="./viewtopic.php?f=3&amp;t=11&amp;start=60">7</a><span class="page-sep">, </span><a href="./viewtopic.php?f=3&amp;t=11&amp;start=70">8</a></span></strong>by <span style="color: #AA0000;" class="username-coloured">admin</span> on Fri Sep 12, 2008 12:00 am 
				</dt>
				<dd class="posts">70 <dfn>Replies</dfn></dd>
				<dd class="views">286 <dfn>Views</dfn></dd>
				<dd class="lastpost"><span><dfn>Last post </dfn>by tuvw784					<a href="./viewtopic.php?f=3&amp;t=11&amp;p=321#p321"><img src="./styles/prosilver/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Fri Jan 16, 2009 10:11 am</span>
				</dd>
			</dl>
		</li>

				</ul>
		<span class="corners-bottom"><span></span></span></div>
	</div>
		<form method="post" action="./viewforum.php?f=3&amp;start=0">
		<fieldset class="display-options">
						<label>Display topics from previous: <select name="st" id="st"><option value="0" selected="selected">All Topics</option><option value="1">1 day</option><option value="7">7 days</option><option value="14">2 weeks</option><option value="30">1 month</option><option value="90">3 months</option><option value="180">6 months</option><option value="365">1 year</option></select></label> 
			<label>Sort by <select name="sk" id="sk"><option value="a">Author</option><option value="t" selected="selected">Post time</option><option value="r">Replies</option><option value="s">Subject</option><option value="v">Views</option></select></label> 
			<label><select name="sd" id="sd"><option value="a">Ascending</option><option value="d" selected="selected">Descending</option></select> <input type="submit" name="sort" value="Go" class="button2" /></label>
		</fieldset>
	</form>
	<hr />
	<div class="topic-actions">
				<div class="pagination">
			 2 topics &bull; Page <strong>1</strong> of <strong>1</strong>		</div>
			</div>
	<p></p><p><a href="./index.php" class="left-box left" accesskey="r">Return to Board index</a></p>
	<form method="post" id="jumpbox" action="./viewforum.php" onsubmit="if(document.jumpbox.f.value == -1){return false;}">

			<fieldset class="jumpbox">
				<label for="f" accesskey="j">Jump to:</label>
			<select name="f" id="f" onchange="if(this.options[this.selectedIndex].value != -1){ document.forms['jumpbox'].submit() }">
							<option value="-1">Select a forum</option>
			<option value="-1">------------------</option>				<option value="3" selected="selected">@@@@@ אקולוקו הסיירת @@@@@</option>
						</select>
			<input type="submit" value="Go" class="button2" />
		</fieldset>
	</form>

	<h3><a href="">Who is online</a></h3>
	<p>Users browsing this forum: <span style="color: #9E8DA7;" class="username-coloured">Alexa [Bot]</span> and 0 guests</p>
</div>

<div id="page-footer">

	<div class="navbar">
		<div class="inner"><span class="corners-top"><span></span></span>

		<ul class="linklist">
			<li class="icon-home"><a href="./index.php" accesskey="h">Board index</a></li>
							<li class="rightside"><a href="./memberlist.php?mode=leaders">The team</a> &bull; All times are UTC </li>
		</ul>

		<span class="corners-bottom"><span></span></span></div>
	</div>
	
<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

	<div class="copyright">Powered by <a href="http://www.phpbb.com/">phpBB</a> &copy; 2000, 2002, 2005, 2007 phpBB Group
			</div>
</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>
	</div>

</body>
</html>