<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="rtl" lang="he" xml:lang="he">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="he" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<title> &bull; לוח בקרה למשתמש &bull; התחבר</title>

<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:      
	
	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'הכנס את מספר העמוד שאליו ברצונך לעבור:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var style_cookie_settings = '; path=/; domain=web3.ekoloko.com';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	
	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/prosilver/template/styleswitcher.js"></script>
<script type="text/javascript" src="./styles/prosilver/template/forum_fn.js"></script>

<link href="./styles/prosilver/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.php?sid=19d08a23c36e6fcfdd5e59d21c25c539&amp;id=1&amp;lang=en" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./styles/prosilver/theme/normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="./styles/prosilver/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./styles/prosilver/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" />

	<link href="./styles/prosilver/theme/bidi.css" rel="stylesheet" type="text/css" media="screen, projection" />

</head>

<body id="phpbb" class="section-ucp rtl">

<div id="wrap">
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<div id="site-description">
				<a href="./index.php?sid=19d08a23c36e6fcfdd5e59d21c25c539" title="עמוד ראשי" id="logo"><img src="./styles/prosilver/imageset/site_logo.gif" width="680" height="123" alt="" title="" /></a>
				<h1></h1>
				<p></p>
				<p style="display: none;"><a href="#start_here">דלג לתוכן</a></p>
			</div>

					<div id="search-box">
				<form action="./search.php?sid=19d08a23c36e6fcfdd5e59d21c25c539" method="post" id="search">
				<fieldset>
					<input name="keywords" id="keywords" type="text" maxlength="128" title="חיפוש מילות מפתח" class="inputbox search" value="חיפוש…" onclick="if(this.value=='חיפוש…')this.value='';" onblur="if(this.value=='')this.value='חיפוש…';" /> 
					<input class="button2" value="חיפוש" type="submit" /><br />
					<a href="./search.php?sid=19d08a23c36e6fcfdd5e59d21c25c539" title="צפה באפשרויות החיפוש המתקדם">חיפוש מתקדם</a> 				</fieldset>
				</form>
			</div>
		
			<span class="corners-bottom"><span></span></span></div>
		</div>

		<div class="navbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<ul class="linklist navlinks">
				<li class="icon-home"><a href="./index.php?sid=19d08a23c36e6fcfdd5e59d21c25c539" accesskey="h">עמוד ראשי</a> </li>

				<li class="rightside"><a href="#" onclick="fontsizeup(); return false;" onkeypress="fontsizeup(); return false;" class="fontsize" title="שנה גודל גופן">שנה גודל גופן</a></li>

							</ul>

			
			<ul class="linklist rightside">
				<li class="icon-faq"><a href="./faq.php?sid=19d08a23c36e6fcfdd5e59d21c25c539" title="שאלות נפוצות">שאלות נפוצות</a></li>
				<li class="icon-register"><a href="./ucp.php?mode=register&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539">הרשמה</a></li>					<li class="icon-logout"><a href="./ucp.php?mode=login&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539" title="התחבר" accesskey="l">התחבר</a></li>
							</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>

	</div>

	<a name="start_here"></a>
	<div id="page-body">
		
		 
<form action="./ucp.php?mode=login&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539" method="post" id="login">
<div class="panel">
	<div class="inner"><span class="corners-top"><span></span></span>

	<div class="content">
		<h2>נא התחבר כדי לגשת ללוח הבקרה למשתמש.</h2>
		
		<fieldset class="fields1">
				<dl>
			<dt><label for="username">שם משתמש:</label></dt>
			<dd><input type="text" tabindex="1" name="username" id="username" size="25" value="" class="inputbox autowidth" /></dd>
		</dl>
		<dl>
			<dt><label for="password">סיסמה:</label></dt>
			<dd><input type="password" tabindex="2" id="password" name="password" size="25" class="inputbox autowidth" /></dd>
			<dd><a href="./ucp.php?mode=sendpassword&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539">שכחתי את סיסמתי</a></dd><dd><a href="./ucp.php?mode=resend_act&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539">שלח מחדש הפעלה לדואר אלקטרוני</a></dd>		</dl>
		
				<dl>
			<dd><label for="autologin"><input type="checkbox" name="autologin" id="autologin" tabindex="4" /> חבר אותי אוטומטית בכל פעם שאבקר ממחשב זה</label></dd>			<dd><label for="viewonline"><input type="checkbox" name="viewonline" id="viewonline" tabindex="5" /> בהתחברות זו אל תאפשר למשתמשים אחרים לראות אם אני מחובר</label></dd>
		</dl>
				<dl>
			<dt>&nbsp;</dt>
			<dd><input type="hidden" name="redirect" value="ucp.php" />
<input type="hidden" name="sid" value="19d08a23c36e6fcfdd5e59d21c25c539" />
<input type="submit" name="login" tabindex="6" value="התחבר" class="button1" /></dd>
		</dl>
	
		</fieldset>
	</div>
	<span class="corners-bottom"><span></span></span></div>
</div>

	<div class="panel">
		<div class="inner"><span class="corners-top"><span></span></span>

		<div class="content">
			<h3>הרשמה</h3>
			<p>כדי להתחבר אתה חייב להיות רשום. ההרשמה לוקחת מספר שניות ומאפשרת לך יכולות גבוהות יותר. המנהל הראשי של המערכת יכול לתת בנוסף הרשאות נוספות למשתמשים רשומים. לפני שאתה מתחבר וודא שאתה מסכים עם תנאי השימוש שלנו וכללי המדיניות. אנא וודא שקראת כל כללי פורום בזמן שאתה גולש במערכת.</p>
			<p><strong><a href="./ucp.php?mode=terms&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539">תנאי שימוש</a> | <a href="./ucp.php?mode=privacy&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539">מדיניות הפרטיות</a></strong></p>
			<hr class="dashed" />
			<p><a href="./ucp.php?mode=register&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539" class="button2">הרשמה</a></p>
		</div>

		<span class="corners-bottom"><span></span></span></div>
	</div>

</form>

</div>

<div id="page-footer">

	<div class="navbar">
		<div class="inner"><span class="corners-top"><span></span></span>

		<ul class="linklist">
			<li class="icon-home"><a href="./index.php?sid=19d08a23c36e6fcfdd5e59d21c25c539" accesskey="h">עמוד ראשי</a></li>
							<li class="rightside"><a href="./memberlist.php?mode=leaders&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539">הצוות</a> &bull; <a href="./ucp.php?mode=delete_cookies&amp;sid=19d08a23c36e6fcfdd5e59d21c25c539">מחק את כל עוגיות המערכת</a> &bull; כל הזמנים הם UTC + 2 שעות [ שעון קיץ ]</li>
		</ul>

		<span class="corners-bottom"><span></span></span></div>
	</div>
	
<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

	<div class="copyright">Powered by <a href="http://www.phpbb.com/">phpBB</a> &copy; 2000, 2002, 2005, 2007 phpBB Group
		<br />מבוסס על <a href="http://www.phpbb.co.il">phpBB.co.il - פורומים בעברית</a>. כל הזכויות שמורות &copy; 2008 - phpBB.co.il.	</div>
</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>
	</div>

</body>
</html>